#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
})

# =============================================================================
# Figure 5 inferential analysis:
# species × CAZyme-class response direction
#
# Tests whether the induced/repressed balance of significant high-confidence
# CAZyme genes differs between Fusarium and Ophiostoma.
#
# The exact canonical plotting table generated by script 35 is used as input,
# ensuring that the statistical tests operate on the same counts displayed
# in Figure 5.
# =============================================================================

ROOT <- normalizePath(".", mustWork = TRUE)

CLASS_FILE <- file.path(
  ROOT,
  "results",
  "publication",
  "cazyme_comparison",
  "plotting_tables",
  "figure5_cazyme_class_response_plotting_table.tsv"
)

AUDIT_FILE <- file.path(
  ROOT,
  "results",
  "publication",
  "cazyme_comparison",
  "comparative_cazyme_audit.tsv"
)

OUTPUT_DIR <- file.path(
  ROOT,
  "results",
  "publication",
  "cazyme_comparison",
  "inferential_tests"
)

dir.create(
  OUTPUT_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)

CLASS_RESULTS_FILE <- file.path(
  OUTPUT_DIR,
  "species_cazyme_class_direction_tests.tsv"
)

OVERALL_RESULTS_FILE <- file.path(
  OUTPUT_DIR,
  "species_cazyme_overall_direction_test.tsv"
)

RUN_INFO_FILE <- file.path(
  OUTPUT_DIR,
  "run_info.tsv"
)

for (path in c(CLASS_FILE, AUDIT_FILE)) {
  if (!file.exists(path)) {
    stop(
      "Missing required canonical input: ",
      path
    )
  }
}

required_cols <- c(
  "species",
  "class",
  "direction",
  "genes",
  "layer",
  "signed_genes"
)

class_data <- read_tsv(
  CLASS_FILE,
  show_col_types = FALSE
)

missing_cols <- setdiff(
  required_cols,
  names(class_data)
)

if (length(missing_cols) > 0L) {
  stop(
    "Class table missing required columns: ",
    paste(missing_cols, collapse = ", ")
  )
}

class_data <- class_data %>%
  mutate(
    species = as.character(species),
    class = as.character(class),
    direction = as.character(direction),
    layer = as.character(layer),
    genes = as.integer(genes)
  )

expected_species <- c("Fusarium", "Ophiostoma")
expected_directions <- c("down", "up")
expected_layers <- c("All significant", "Secreted")
expected_classes <- c("AA", "CBM", "CE", "GH", "GT", "PL")

if (!setequal(unique(class_data$species), expected_species)) {
  stop("Unexpected species values in canonical Figure 5 table.")
}

if (!setequal(unique(class_data$direction), expected_directions)) {
  stop("Unexpected direction values in canonical Figure 5 table.")
}

if (!setequal(unique(class_data$layer), expected_layers)) {
  stop("Unexpected layer values in canonical Figure 5 table.")
}

if (!setequal(unique(class_data$class), expected_classes)) {
  stop("Unexpected CAZyme classes in canonical Figure 5 table.")
}

if (anyNA(class_data$genes) || any(class_data$genes < 0L)) {
  stop("Invalid gene counts in canonical Figure 5 table.")
}

dup <- class_data %>%
  count(
    species,
    class,
    direction,
    layer
  ) %>%
  filter(n != 1L)

if (nrow(dup) > 0L) {
  stop(
    "Expected exactly one row per species × class × direction × layer."
  )
}

safe_fisher <- function(a, b, c, d) {

  mat <- matrix(
    c(a, b, c, d),
    nrow = 2,
    byrow = TRUE,
    dimnames = list(
      species = c("Fusarium", "Ophiostoma"),
      direction = c("Induced", "Repressed")
    )
  )

  if (
    sum(mat[1, ]) == 0L ||
    sum(mat[2, ]) == 0L
  ) {
    return(
      tibble(
        odds_ratio = NA_real_,
        ci_lower = NA_real_,
        ci_upper = NA_real_,
        pvalue = NA_real_,
        testable = FALSE
      )
    )
  }

  ft <- fisher.test(
    mat,
    alternative = "two.sided",
    conf.int = TRUE
  )

  tibble(
    odds_ratio = unname(ft$estimate),
    ci_lower = unname(ft$conf.int[1]),
    ci_upper = unname(ft$conf.int[2]),
    pvalue = ft$p.value,
    testable = TRUE
  )
}

wide <- class_data %>%
  select(
    species,
    class,
    direction,
    layer,
    genes
  ) %>%
  pivot_wider(
    names_from = c(species, direction),
    values_from = genes,
    values_fill = 0
  )

class_tests <- wide %>%
  rowwise() %>%
  mutate(
    fisher = list(
      safe_fisher(
        Fusarium_up,
        Fusarium_down,
        Ophiostoma_up,
        Ophiostoma_down
      )
    )
  ) %>%
  unnest(fisher) %>%
  ungroup() %>%
  mutate(
    fusarium_total = Fusarium_up + Fusarium_down,
    ophiostoma_total = Ophiostoma_up + Ophiostoma_down,
    fusarium_induced_percent = if_else(
      fusarium_total > 0,
      100 * Fusarium_up / fusarium_total,
      NA_real_
    ),
    ophiostoma_induced_percent = if_else(
      ophiostoma_total > 0,
      100 * Ophiostoma_up / ophiostoma_total,
      NA_real_
    ),
    effect_direction = case_when(
      !testable ~ "not testable",
      odds_ratio > 1 ~ "more induction-biased in Fusarium",
      odds_ratio < 1 ~ "more induction-biased in Ophiostoma",
      TRUE ~ "no directional difference"
    )
  )

# BH correction within each displayed Figure 5 layer.
class_tests <- class_tests %>%
  group_by(layer) %>%
  mutate(
    padj_within_layer = {
      out <- rep(NA_real_, n())
      idx <- which(testable)
      if (length(idx) > 0L) {
        out[idx] <- p.adjust(
          pvalue[idx],
          method = "BH"
        )
      }
      out
    }
  ) %>%
  ungroup()

# BH correction across all valid class-level tests.
class_tests$padj_all_class_tests <- NA_real_
valid_idx <- which(class_tests$testable)

if (length(valid_idx) > 0L) {
  class_tests$padj_all_class_tests[valid_idx] <- p.adjust(
    class_tests$pvalue[valid_idx],
    method = "BH"
  )
}

class_tests <- class_tests %>%
  mutate(
    significant_within_layer = (
      testable &
      !is.na(padj_within_layer) &
      padj_within_layer < 0.05
    ),
    significant_all_class_tests = (
      testable &
      !is.na(padj_all_class_tests) &
      padj_all_class_tests < 0.05
    )
  ) %>%
  arrange(
    factor(
      layer,
      levels = expected_layers
    ),
    pvalue,
    class
  )

write_tsv(
  class_tests,
  CLASS_RESULTS_FILE
)

# -----------------------------------------------------------------------------
# Overall direction from gene-level canonical audit
# -----------------------------------------------------------------------------

audit <- read_tsv(
  AUDIT_FILE,
  show_col_types = FALSE
)

if (any(audit$status != "PASS")) {
  stop("At least one CAZyme audit row is not PASS.")
}

fus <- audit %>% filter(species == "Fusarium")
oph <- audit %>% filter(species == "Ophiostoma")

if (nrow(fus) != 1L || nrow(oph) != 1L) {
  stop("Expected exactly one CAZyme audit row per species.")
}

for (i in seq_len(nrow(audit))) {
  if (
    audit$upregulated_genes[i] +
    audit$downregulated_genes[i] !=
    audit$unique_gene_count[i]
  ) {
    stop(
      "Direction counts do not sum to unique_gene_count for ",
      audit$species[i]
    )
  }
}

overall_matrix <- matrix(
  c(
    fus$upregulated_genes,
    fus$downregulated_genes,
    oph$upregulated_genes,
    oph$downregulated_genes
  ),
  nrow = 2,
  byrow = TRUE,
  dimnames = list(
    species = c("Fusarium", "Ophiostoma"),
    direction = c("Induced", "Repressed")
  )
)

overall_ft <- fisher.test(
  overall_matrix,
  alternative = "two.sided",
  conf.int = TRUE
)

overall_result <- tibble(
  comparison = "All significant high-confidence CAZymes",
  fusarium_induced = fus$upregulated_genes,
  fusarium_repressed = fus$downregulated_genes,
  ophiostoma_induced = oph$upregulated_genes,
  ophiostoma_repressed = oph$downregulated_genes,
  fusarium_induced_percent = (
    100 * fus$upregulated_genes / fus$unique_gene_count
  ),
  ophiostoma_induced_percent = (
    100 * oph$upregulated_genes / oph$unique_gene_count
  ),
  odds_ratio = unname(overall_ft$estimate),
  ci_lower = unname(overall_ft$conf.int[1]),
  ci_upper = unname(overall_ft$conf.int[2]),
  pvalue = overall_ft$p.value,
  interpretation = case_when(
    unname(overall_ft$estimate) > 1 ~
      "more induction-biased in Fusarium",
    unname(overall_ft$estimate) < 1 ~
      "more induction-biased in Ophiostoma",
    TRUE ~
      "no directional difference"
  )
)

write_tsv(
  overall_result,
  OVERALL_RESULTS_FILE
)

run_info <- tibble(
  field = c(
    "script",
    "class_input",
    "cazyme_audit_input",
    "class_output",
    "overall_output",
    "statistical_test",
    "alternative",
    "multiple_testing",
    "odds_ratio_definition",
    "provenance_note"
  ),
  value = c(
    "workflow/scripts/41_test_cazyme_class_direction.R",
    "results/publication/cazyme_comparison/plotting_tables/figure5_cazyme_class_response_plotting_table.tsv",
    "results/publication/cazyme_comparison/comparative_cazyme_audit.tsv",
    "results/publication/cazyme_comparison/inferential_tests/species_cazyme_class_direction_tests.tsv",
    "results/publication/cazyme_comparison/inferential_tests/species_cazyme_overall_direction_test.tsv",
    "Two-sided Fisher exact test on species x induced/repressed 2x2 table",
    "two-sided",
    "Benjamini-Hochberg within each layer and across all valid class-level tests",
    "OR > 1 = relatively more induction-biased in Fusarium; OR < 1 = relatively more induction-biased in Ophiostoma",
    "Class-level tests consume the exact canonical plotting counts written by script 35."
  )
)

write_tsv(
  run_info,
  RUN_INFO_FILE
)

cat("\n")
cat("============================================================\n")
cat("FIGURE 5 CAZYME DIRECTION TESTS COMPLETE\n")
cat("============================================================\n\n")

cat("Overall high-confidence CAZyme direction:\n")
print(overall_result)

cat("\nSignificant class-level tests after BH within layer:\n")

sig <- class_tests %>%
  filter(significant_within_layer) %>%
  select(
    layer,
    class,
    Fusarium_up,
    Fusarium_down,
    Ophiostoma_up,
    Ophiostoma_down,
    odds_ratio,
    ci_lower,
    ci_upper,
    pvalue,
    padj_within_layer,
    effect_direction
  )

if (nrow(sig) == 0L) {
  cat("  None.\n")
} else {
  print(sig)
}

cat("\nOutputs:\n")
cat("  ", CLASS_RESULTS_FILE, "\n", sep = "")
cat("  ", OVERALL_RESULTS_FILE, "\n", sep = "")
cat("  ", RUN_INFO_FILE, "\n", sep = "")
cat("\nPASS: Figure 5 inferential tests completed.\n")
